### ISSUE TITLE
Docker issue while using windows container

### ISSUE THREAD

**Issue by manudeep936** [bfv/docker4oe#3]
Hi i am getting the following error while pulling image from hub or while running the existing image

Error response from daemon: Get https://mcr.microsoft.com/v2/: invalid proxy URL port "port".
please help me

**Comment by bfv** [comment]
I have no clue which image you're referring to. Statement from Progress: _Windows Server Core is not certified by Progress for any OpenEdge version_.  As far as I'm concerned this will not work.

**Comment by manudeep936** [comment]
i am try to dockerize my dotnet application. For that i am trying to use base image
docker pull mcr.microsoft.com/dotnet/framework/sdk. while i am trying to pull image i am getting the following error
![Capture](https://user-images.githubusercontent.com/39149272/54746041-2b780c00-4bf1-11e9-8a8c-99309a4b4e5f.PNG)

**Comment by manudeep936** [comment]
i am try to dockerize my dotnet application. For that i am trying to use base image
docker pull mcr.microsoft.com/dotnet/framework/sdk. while i am trying to pull image i am getting the following error
![Capture](https://user-images.githubusercontent.com/39149272/54746078-4c406180-4bf1-11e9-83aa-e12e9ac4f4cb.PNG)

**Comment by bfv** [comment]
Ah, I that case indeed this issue can be closed. This repo has nothing to do with .NET.
